---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install certain python modules for docker
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      with_items:
      - { name: docker, version: 2.0.0 }
    # - name: Stop the running docker
    #   shell: docker stop cardio
    # - name: Remove the docker
    #   shell: docker rm -f cardio
    # - name: Remove image of the docker
    #   shell: docker image rm -f prateksha/cardio:latest
    - name: Pull image of cardio
      docker_image:
        name: prateksha/cardio
    - name: Download the latest docker and run
      shell: docker run -d -p 3000:3000 --name cardio prateksha/cardio:latest
